# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 660bc843b7164e153591be637782542f91c1097d7c810bcdbc3669987b1f621ae6ec676f3b63fa51c374be990d8534669aeb58265a0f6f81983dc908a30fdb92

test:
  secret_key_base: 6325df38c31e4014423094aea35f073c2076815eb7b8f304ddf5d46b45d5a2e36130f177ca7bdaf79a6090c8b3354952939c08ce75e5242b6630499d77ac61d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
